config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  # Active Admin routes ################################################################################################

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Redmon::App => '/admin/redmon'
  end

  # Authentication #####################################################################################################

  resources :user_sessions, only: [:new, :create, :destroy] do
    collection do
      get :forgot_password
    end
  end
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'logout' => 'user_sessions#destroy'

  #get 'oauths/oauth'
  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback' => 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  # Resources ##########################################################################################################

  resources :users,                 only: [:index, :show, :create, :update, :destroy] do
    collection do
      post :update_club
      post :update_team
      post :upload
      get :current
      get :unimpersonate
    end
    member do
      get :season_stats
      get :playing_career
      get :prior_games
      get :team_games
      get :impersonate
    end

    #resources :player_profiles, shallow: true, only: [:index]
    resources :player_equipment,   only: [:index, :create, :destroy], shallow: true
    resources :teams,               only: [:show]

    resource :awards
  end

  resources :associations,  only: [:index, :show, :create, :update, :destroy] do
    resources :clubs,       only: [:index], shallow: true
    resources :divisions,   only: [:index], shallow: true
    resources :users,       only: [:index], shallow: true

    collection do
      post :upload
    end
  end

  resources :clubs,         only: [:index, :show, :create, :update, :destroy] do
    resources :teams,       only: [:index], shallow: true
    resources :users,       only: [:index], shallow: true

    collection do
      post :upload
      get :import
      post :import
    end
  end

  resources :divisions,     only: [:show] do
    resources :teams,       only: [:index], shallow: true
  end

  resources :teams,         only: [:show, :create, :update, :destroy] do
    member do
      #get :last_results
      get :previous_meetings
    end

    collection do
      get :csv_upload
      post :csv_upload
      # get :previous_games
    end
  end
  #   member do
  #     get :subteams
  #   end
  # end

  resources :positions,     only: [:index]

  resources :equipment,     only: [:index] do
    collection do
      get :csv_upload
      post :csv_upload
    end
  end

  resources :brands,        only: [:index]
  resources :games,         only: [:show] do
    resources :player_results, only: [:index, :create, :update], shallow: true do
      collection do
        get :from_game
      end
    end
    member do
      get :weather_forecast
    end
  end

  resources :leagues,       only: [] do
    member do
      get :standings
    end
  end

  resources :player_results, only: [] do
    collection do
      get :from_games
    end
  end

  resources :articles, only: [:index, :show]


  # Static pages #######################################################################################################

  root 'static#index'
  get 'actions' =>  'static#actions'
  get 'dashboard' => 'static#dashboard'
  get 'static/login'
  #get 'content/*url' => 'static#content', format: false

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login #, except: [:destroy]
  skip_authorization_check only: [:new, :create, :destroy]

  def new
    @user = User.new
    #@twitter_url = sorcery_login_url('twitter')
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to(root_path + "#/users/#{@user.id}/dashboard",  notice: 'Login successful')
      #redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Please enter a valid email and password combination'
      @email = params[:email]
      @password = params[:password]
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(new_user_session_path)
  end
end

app/views/user_sessions/forgot_password.slim
div Forgot Password
a> href='/welcome' Back to Welcome

app/views/user_sessions/new.slim
body.login
  / SVG ICON SYMBOLS FOR FB, Twitter, G+
  svg.hidden xmlns="http://www.w3.org/2000/svg"
    symbol#facebook-icon viewbox=("0 0 42 42")
      path d=("M23.5 40h-8v-19.5h-4v-6.7h4v-4c0-5.5 2.3-8.7 8.6-8.7h5.3v6.7h-3.3c-2.5 0-2.7.9-2.7 2.7v3.4h6l-.7 6.7h-5.3v19.4z")
    symbol#twitter-icon viewbox=("0 0 42 42")
      path d=("M40 9.6c-1.4.6-2.9 1-4.5 1.2 1.6-.9 2.8-2.4 3.4-4.2-1.5.9-3.2 1.5-5 1.8-1.3-1.5-3.3-2.4-5.6-2.4-4.3 0-7.8 3.4-7.8 7.6 0 .6.1 1.2.2 1.7-6.5-.3-12.2-3.3-16.1-7.9-.6 1.1-1 2.4-1 3.8 0 2.6 1.4 4.9 3.5 6.3-1.3 0-2.5-.4-3.5-.9v.1c0 3.7 2.7 6.7 6.3 7.4-.7.2-1.3.3-2.1.3-.5 0-1 0-1.5-.1 1 3 3.9 5.2 7.3 5.3-2.7 2-6 3.2-9.7 3.2-.6 0-1.2 0-1.9-.1 3.5 2 7.5 3.3 12 3.3 14.3 0 22.2-11.5 22.2-21.5v-1c1.4-1.1 2.8-2.4 3.8-3.9z")
    symbol#google-icon viewbox=("0 0 42 42")
      path d=("M22.7 3.9h-9.8s-9.9.2-9.9 8.8c0 8.5 8.6 7.5 8.6 7.5v2.2c0 .9 1.2.6 1.3 2.4-.6 0-12-.3-12 7.4.1 7.7 10.1 7.3 10.1 7.3s11.6.5 11.6-9.1c0-5.8-6.6-7.6-6.6-9.9 0-2.3 5-3 5-8.4 0-3.3-.3-5.2-2.8-6.4 0-.8 4.5-.3 4.5-1.8zm-3.2 27.2c.2 3-2.9 5.7-6.9 5.9-4 .3-7.5-1.9-7.7-4.9-.2-3 2.9-5.7 6.9-5.9 4.1-.3 7.5 1.9 7.7 4.9zm-5.9-12.9c-2.4.7-5.1-1.6-6-5-.9-3.4.3-6.7 2.7-7.4 2.4-.7 5.1 1.6 6 5 .9 3.4-.3 6.7-2.7 7.4zm20.6-7.4v-6.9h-2v6.9h-6.8v2h6.8v6.9h2v-6.9h6.8v-2h-6.8z")
    symbol#email-icon viewbox=("0 0 16 16")
      path d=("M15,2H1C0.4,2,0,2.4,0,3v10c0,0.6,0.4,1,1,1h14c0.6,0,1-0.4,1-1V3C16,2.4,15.6,2,15,2z M5.7,9L8,10.6L10.3,9l4,4H1.7L5.7,9\n\t\tz M1,12.3V5.8l3.8,2.6L1,12.3z M11.1,8.4L15,5.8v6.5L11.1,8.4z M15,3v1.6l0,0L8,9.4L1,4.6V3H15z")
    symbol#lock-icon viewbox=("0 0 16 16")
      path d=("M8,0C5.2,0,3,2.3,3,5.1V6H2C1.4,6,1,6.4,1,7v8c0,0.6,0.4,1,1,1h12c0.6,0,1-0.4,1-1V7c0-0.6-0.4-1-1-1h-1V5.1\n\t\tC13,2.3,10.8,0,8,0z M4,5.1C4,2.8,5.8,1,8,1s4,1.8,4,4.1V6H4V5.1z M14,15H2V7h12V15z M10,11c0-1.1-0.9-2-2-2s-2,0.9-2,2s0.9,2,2,2\n\t\tS10,12.1,10,11z M8,12c-0.6,0-1-0.4-1-1s0.4-1,1-1s1,0.4,1,1S8.6,12,8,12z")
    symbol#right-arrow-icon viewbox=("0 0 16 16")
      polygon points=("5,0 3,2 9,8 3,14 5,16 13,8 ")

  header
    #masthead
      .container
        .logo
          img.center-block.img-responsive alt="" src="/img/CT-logo-3x.png" /
  .container
    .row
      .container
        .col-md-12
          .panel.panel-main.panel-default.gradient
            .panel-body
              h2.login-title Log In to your Account

              - flash.each do |name, msg|
                .alert.alert-danger role="alert"
                  p
                    = msg
              /.alert.alert-danger role="alert"
                | Please enter a valid email and password combination
              = form_tag user_sessions_path, method: :post, autocomplete: 'off'
                fieldset
                  .form-group
                    label.control-label.sr-only for="email" Email address
                    / .input-group
                    /   .input-group-addon
                    /     svg
                    /       use xlink:href="#email-icon" xmlns:xlink="http://www.w3.org/1999/xlink"
                    input#emailAddress type="text" class="form-control" name="email" placeholder="email address" value="#{@email}" /
                  .form-group
                    label.control-label.sr-only for="password" aria-hidden="true" Password
                    / .input-group
                      / .input-group-addon
                      /   svg
                      /     use xlink:href="#lock-icon" xmlns:xlink="http://www.w3.org/1999/xlink"
                    input#password type="password" class="form-control" name="password" placeholder="password" value="#{@password}" /
                  .form-group
                    button#signin.btn.btn-primary.btn-block.text-uppercase type="submit" name="signin"
                      | Log In
                      svg
                        use xlink:href="#right-arrow-icon" xmlns:xlink="http://www.w3.org/1999/xlink"

          /.panel.panel-default.gradient.login-transparent
            .login-register
              .highlight
                a.underline> href='/#/join' Create a Free Account
                ' &nbsp;&gt;
              .white
                ' Sign up for a free account and start recording your story and taking control of your destiny

              /.row.social-log-in
                .center-block.text-center.divider
                  span.text-uppercase
                    | Or Log In with
                ul.list-inline.text-center
                  li.facebook
                    = link_to auth_at_provider_path(provider: :facebook), class: 'btn btn-default', title: 'Log In with Facebook' do
                      svg
                        use xlink:href="#facebook-icon" xmlns:xlink="http://www.w3.org/1999/xlink"
                  li.twitter
                    = link_to auth_at_provider_path(provider: :twitter), class: 'btn btn-default', title: 'Log In with Twitter' do
                      svg
                        use xlink:href="#twitter-icon" xmlns:xlink="http://www.w3.org/1999/xlink"
                  li.google-plus
                    = link_to auth_at_provider_path(provider: :google), class: 'btn btn-default', title: 'Log In with Google' do
                      svg
                        use xlink:href="#google-icon" xmlns:xlink="http://www.w3.org/1999/xlink"

/div style='position:absolute;top:0;left:0;right:0;height:50%;text-align:center;overflow:hidden'
  img src='/img/tmp/football-soccer.jpg' style='height:400px'

/div style='position:absolute;bottom:0;left:0;right:0;height:50%;text-align:center;padding-top:20px'
  - flash.each do |name, msg|
    = content_tag :div, msg, class: [name, 'alert-warning']
  = form_tag user_sessions_path, :method => :post, :class => 'form-horizontal'
    .form-group
      = label_tag :email, 'Email', :class => 'col-sm-2 control-label'
      .col-sm-10
        = text_field_tag :email, '', :class => 'form-control'
    .form-group
      = label_tag :password, 'Password', :class => 'col-sm-2 control-label'
      .col-sm-10
        = password_field_tag :password, '', :class => 'form-control'
    .actions
      = submit_tag 'Login', :class => 'btn btn-primary btn-lg'
  p &nbsp;
  p &nbsp;
  .share-element style='transform:none;transition:none'
    ui style='list-style:none'
      li.facebook style='font-size:36px;display:inline'
        = link_to auth_at_provider_path(provider: :facebook), style: 'display:inline' do
          span.social_facebook_square
          span.sr_only
          /| Login with Facebook

      li.twitter style='font-size:36px;display:inline'
        = link_to auth_at_provider_path(provider: :twitter), style: 'display:inline' do
          span.social_twitter_square
          span.sr_only

      li.google style='font-size:36px;display:inline;vertical-align:middle'
        = link_to auth_at_provider_path(provider: :google), style: 'display:inline' do
          span.social_googleplus_square
          span.sr_only